import mongoose from "mongoose";
import Company from "../models/companies.model.js";
import FormLibrary from "../models/formLibraries.model.js";
import FormSection from "../models/formSection.model.js";
import FormSubSection from "../models/formSubSection.model.js";
import FormConfigurationField from "../models/formConfigurationField.model.js";
import DropDownLibraries from "../models/dropDownLibraries.model.js";
import DropDownValue from "../models/dropDownValues.model.js";
import User from "../models/user.model.js";

const seedDatabase = async () => {
  try {
    // Seed Companies if empty
    let company = await Company.findOne();
    if (!company) {
      const insertedCompanies = await Company.insertMany([
        {
          name: "Myslice_ATS",
          phoneNo: "23-456-7890",
          address: "123 Tech Street, Silicon Valley, CA",
          country: "USA",
          logo: "logo1.png",
          companyDomain: "techcorp.com",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      company = insertedCompanies[0];
      console.log("✅ Companies seeded.");
    } else {
      console.log("ℹ️ Companies already exist. Skipping seeding.");
    }

    // Seed FormLibraries if empty
    let formLibrary = await FormLibrary.findOne();
    if (!formLibrary) {
      const insertedFormLibraries = await FormLibrary.insertMany([
        {
          name: "Job Config Form",
          // Ideally link company_id to the company created above
          companyId: company._id, // or you can fetch the company _id here dynamically
          isEnabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      formLibrary = insertedFormLibraries[0];
      console.log("✅ FormLibraries seeded.");
    } else {
      console.log("ℹ️ FormLibraries already exist. Skipping seeding.");
    }
    // Seed FormSection if empty
    let formSection = await FormSection.findOne();
    let formSections = [];
    if (!formSection) {
      formSections = await FormSection.insertMany([
        {
          formLibraryId: formLibrary._id, // Replace with actual ObjectId if you're using Mongo refs
          name: "Job Details",
          sortOrder: 1,
          isEnabled: true,
          key: "job_details",
          companyId: company._id, // Replace with actual ObjectId if needed
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          name: "Recruitment Team",
          sortOrder: 2,
          isEnabled: true,
          key: "recruitment_team",
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          name: "Post & Promote",
          sortOrder: 3,
          isEnabled: true,
          key: "post_promote",
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          name: "Candidate Evaluation",
          sortOrder: 4,
          isEnabled: true,
          key: "candidate_evaluation",
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      console.log("✅ FormSection seeded.");
    } else {
      console.log("ℹ️ FormSection already exist. Skipping seeding.");
    }

    // Map section keys to IDs for use in FormSubSection
    const sectionMap = {};
    formSections.forEach((section) => {
      sectionMap[section.key] = section._id;
    });

    // Seed User if empty
    let adminUser;
    const userCount = await User.countDocuments();
    console.log(`User count: ${userCount}`);
    if (userCount === 0) {
      [adminUser] = await User.insertMany([
        {
          name: "Admin",
          companyId: company._id,
          email: "admin@gmail.com",
          password:
            "$2b$10$26ibo2LwUcWjMkA8LGHlQeJOytI1xqn/H6Y.WR3BHdlPNpLxUYakO",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      console.log("✅ User seeded.");
    } else {
      console.log("ℹ️ User already exist. Skipping seeding.");
    }

    // Seed dropDownLibraries if empty
    let dropDownLibraries = [];
    const dropDownLibrariesCount = await DropDownLibraries.countDocuments();
    console.log(`dropDownLibrariesCount: ${dropDownLibrariesCount}`);
    if (dropDownLibrariesCount === 0) {
      dropDownLibraries = await DropDownLibraries.insertMany([
        {
          name: "Minimum Qualification",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Job Type",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Job Mode",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Eligible Work Visas",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Client Work Arrangement",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Job Category",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Job Ad Language",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      console.log("✅ dropDownLibraries seeded.");
    } else {
      console.log("ℹ️ DropDownLibraries already exist. Skipping seeding.");
    }

    // Create a map of drop down names to IDs
    const dropDownMap = {};
    dropDownLibraries.forEach((dropdown) => {
      dropDownMap[dropdown.name] = dropdown._id;
    });

    // Seed Drop Down value if empty
    const dropDownValueCount = await DropDownValue.countDocuments();
    console.log(`Drop Down Value count: ${dropDownValueCount}`);
    if (dropDownValueCount === 0) {
      await DropDownValue.insertMany([
        {
          name: "High School Diploma",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Associate's Degree",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Bachelor's Degree",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Master's Degree",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Doctorate (PhD)",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Diploma",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "No Formal Education",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "fulltime",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Type"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "parttime",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Type"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "contract",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Type"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "c2h",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Type"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "temporary",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Type"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "internship",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Type"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "freelancer",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Type"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "hybrid",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Mode"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "onsite",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Mode"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "remote",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Mode"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "H-1B",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "CPT",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "OPT",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "STEM",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "H-4 EAD",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "L-2 EAD",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "GC",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "USC",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "TN",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "E-3",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "fulltime",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Client Work Arrangement"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "c2h",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Client Work Arrangement"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "contract",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Client Work Arrangement"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Information Technology (IT) & Software",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Engineering & Manufacturing",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Healthcare & Life Sciences",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Finance & Accounting",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Sales & Marketing",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Human Resources & Recruitment",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Administration & Operations",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Legal & Compliance",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Customer Support & Service",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Education & Training",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Creative & Media",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Construction & Real Estate",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Hospitality & Travel",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Government & Public Sector",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Science & Research",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Category"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "English",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Ad Language"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Hindi",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Ad Language"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Spanish",
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          isActive: true,
          companyId: company._id,
          isDeleted: false,
          isMandatory: true,
          dropdownId: dropDownMap["Job Ad Language"],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      console.log("✅ DropDownValue seeded.");
    } else {
      console.log("ℹ️ DropDownValue already exist. Skipping seeding.");
    }

    // Seed FormSubSection if empty
    let formSubSection = await FormSubSection.findOne();
    let formSubSections = [];
    if (!formSubSection) {
      formSubSections = await FormSubSection.insertMany([
        {
          formSectionId: sectionMap["job_details"],
          formLibraryId: formLibrary._id,
          key: "internal",
          name: "Internal",
          sortOrder: 1,
          isEnabled: true,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["job_details"],
          formLibraryId: formLibrary._id,
          key: "external",
          name: "External",
          sortOrder: 2,
          isEnabled: true,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["recruitment_team"],
          formLibraryId: formLibrary._id,
          key: "internal_team",
          name: "Internal Team",
          sortOrder: 3,
          isEnabled: true,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["recruitment_team"],
          formLibraryId: formLibrary._id,
          key: "external_team",
          name: "External Team",
          sortOrder: 4,
          isEnabled: true,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["post_promote"],
          formLibraryId: formLibrary._id,
          key: "career_job_config_basic",
          name: "Job Config Basic",
          sortOrder: 5,
          isEnabled: true,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["post_promote"],
          formLibraryId: formLibrary._id,
          key: "career_job_config_advance",
          name: "Job Config Advance",
          sortOrder: 6,
          isEnabled: true,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["post_promote"],
          formLibraryId: formLibrary._id,
          key: "career_job_applicant",
          name: "Job Applicant",
          sortOrder: 7,
          isEnabled: true,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["post_promote"],
          formLibraryId: formLibrary._id,
          key: "career_application_received",
          name: "Application Received",
          sortOrder: 8,
          isEnabled: false,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["post_promote"],
          formLibraryId: formLibrary._id,
          key: "career_application_reject",
          name: "Application Reject",
          sortOrder: 9,
          isEnabled: false,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["candidate_evaluation"],
          formLibraryId: formLibrary._id,
          key: "candidate_evaluation_questionary",
          name: "Questionary",
          sortOrder: 10,
          isEnabled: false,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formSectionId: sectionMap["candidate_evaluation"],
          formLibraryId: formLibrary._id,
          key: "candidate_evaluation_scorecard",
          name: "Scorecard",
          sortOrder: 11,
          isEnabled: false,
          companyId: company._id,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      console.log("✅ FormSection seeded.");
    } else {
      console.log("ℹ️ FormSubSection already exist. Skipping seeding.");
    }

    // Map subSection keys to IDs for later use
    const subSectionMap = {};
    formSubSections.forEach((subSection) => {
      subSectionMap[subSection.key] = subSection._id;
    });

    // Seed FormConfigField if empty
    const formConfigFieldCount = await FormConfigurationField.countDocuments();
    console.log(`formConfigFieldCount : ${formConfigFieldCount}`);
    if (formConfigFieldCount === 0) {
      await FormConfigurationField.insertMany([
        {
          formLibraryId: formLibrary._id,
          key: "internal_job_name",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Job Name",
          displayName: "Job Name",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_job_id",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 1,
          gridGroup: 2,
          labelName: "Job ID",
          displayName: "Job ID",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_minimum_qualification",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 2,
          gridGroup: 1,
          labelName: "Minimum Qualification",
          displayName: "Minimum Qualification",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: false,
          isDisabled: true,
          isDraggabled: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_experience",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 2,
          gridGroup: 2,
          labelName: "Experience",
          displayName: "Experience",
          fieldType: "number",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: true,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_job_type",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"], // dynamic subsection ID
          formSectionId: sectionMap["job_details"], // dynamic section ID
          sortOrder: 3,
          gridGroup: 1,
          labelName: "Job Type",
          displayName: "Job Type",
          fieldType: "dropdown",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          dropdownId: dropDownMap["Job Type"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_position_duration",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 4,
          gridGroup: 1,
          labelName: "Position Duration",
          displayName: "Position Duration",
          fieldType: "number",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_total_position",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 3,
          gridGroup: 2,
          labelName: "No. Of Positions",
          displayName: "No. Of Positions",
          fieldType: "number",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: true,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_job_mode",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 5,
          gridGroup: 1,
          labelName: "Job Mode",
          displayName: "Job Mode",
          fieldType: "dropdown",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          dropdownId: dropDownMap["Job Mode"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_in_office_days",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 6,
          gridGroup: 1,
          labelName: "In-Office Days",
          displayName: "In-Office Days",
          fieldType: "number",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_job_location",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 4,
          gridGroup: 2,
          labelName: "Job Location",
          displayName: "Job Location",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_candidate_pay_rate_salary",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 7,
          gridGroup: 1,
          labelName: "Candidate Pay Rate/Salary",
          displayName: "Candidate Pay Rate/Salary",
          fieldType: "number",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: false,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "internal_work_visa",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 5,
          gridGroup: 2,
          labelName: "Eligible Work Visas",
          displayName: "Eligible Work Visas",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: true,
          isDraggabled: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_job_name",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Job Name",
          displayName: "Job Name",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_job_id",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 1,
          gridGroup: 2,
          labelName: "Job ID",
          displayName: "Job ID",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "client_name",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 2,
          gridGroup: 1,
          labelName: "Client Name",
          displayName: "Client Name",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "end_client_name",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 2,
          gridGroup: 2,
          labelName: "End Client Name",
          displayName: "End Client Name",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "client_manager",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 3,
          gridGroup: 1,
          labelName: "Client Manager",
          displayName: "Client Manager",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: true,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "client_job_id",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 3,
          gridGroup: 2,
          labelName: "Client Job ID",
          displayName: "Client Job ID",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_minimum_qualification",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 4,
          gridGroup: 1,
          labelName: "Minimum Qualification",
          displayName: "Minimum Qualification",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          dropdownId: dropDownMap["Minimum Qualification"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_experience",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 4,
          gridGroup: 2,
          labelName: "Experience",
          displayName: "Experience",
          fieldType: "number",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_job_type",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 5,
          gridGroup: 1,
          labelName: "Client Work Arrangement",
          displayName: "Job Type",
          fieldType: "dropdown",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          dropdownId: dropDownMap["Client Work Arrangement"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_position_duration",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 6,
          gridGroup: 1,
          labelName: "Position Duration",
          displayName: "Position Duration",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_total_position",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 5,
          gridGroup: 2,
          labelName: "No. Of Positions",
          displayName: "No. Of Positions",
          fieldType: "number",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_job_mode",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 7,
          gridGroup: 1,
          labelName: "Job Mode",
          displayName: "Job Mode",
          fieldType: "dropdown",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          dropdownId: dropDownMap["Job Mode"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_in_office_days",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 8,
          gridGroup: 1,
          labelName: "In-Office Days",
          displayName: "In-Office Days",
          fieldType: "number",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_job_location",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 6,
          gridGroup: 2,
          labelName: "Job Location",
          displayName: "Job Location",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_candidate_pay_rate_salary",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 9,
          gridGroup: 1,
          labelName: "Candidate Pay Rate/Salary",
          displayName: "Candidate Pay Rate/Salary",
          fieldType: "number",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: false,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "external_work_visa",
          companyId: company._id,
          formSubSectionId: subSectionMap["external"],
          formSectionId: sectionMap["job_details"],
          sortOrder: 7,
          gridGroup: 2,
          labelName: "Eligible Work Visas",
          displayName: "Eligible Work Visas",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          dropdownId: dropDownMap["Eligible Work Visas"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "recruitment_manager",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal_team"],
          formSectionId: sectionMap["recruitment_team"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Recruiter Manager",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "assigned_recruiters",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal_team"],
          formSectionId: sectionMap["recruitment_team"],
          sortOrder: 1,
          gridGroup: 2,
          labelName: "Assigned Recruiter(s)",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "team_notes",
          companyId: company._id,
          formSubSectionId: subSectionMap["internal_team"],
          formSectionId: sectionMap["recruitment_team"],
          sortOrder: 2,
          gridGroup: 1,
          labelName: "Team Notes",
          fieldType: "textarea",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "agency_names",
          companyId: company._id,
          formSubSectionId: subSectionMap["external_team"],
          formSectionId: sectionMap["recruitment_team"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Agency Name(s)",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "recruiters",
          companyId: company._id,
          formSubSectionId: subSectionMap["external_team"],
          formSectionId: sectionMap["recruitment_team"],
          sortOrder: 1,
          gridGroup: 2,
          labelName: "Recruiter(s)",
          fieldType: "dropdown",
          isMultiSelect: true,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "invitation_message",
          companyId: company._id,
          formSubSectionId: subSectionMap["external_team"],
          formSectionId: sectionMap["recruitment_team"],
          sortOrder: 2,
          gridGroup: 1,
          labelName: "Invitation Message",
          fieldType: "textarea",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_ad_title",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_basic"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Job Ad Title",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_category",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_basic"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 2,
          labelName: "Job Category",
          fieldType: "dropdown",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          dropdownId: dropDownMap["Job Category"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: "683ad009053814e9b60863f6",
          key: "job_ad_language",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_basic"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 2,
          gridGroup: 1,
          labelName: "Job Ad Language",
          fieldType: "dropdown",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          dropdownId: dropDownMap["Job Ad Language"],
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_client_name",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_advance"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Client Name",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "pay_rate_salary",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_advance"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 2,
          gridGroup: 1,
          labelName: "Pay Rate/Salary",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: true,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "enabled_chat_with_recruiter",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_advance"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 3,
          gridGroup: 1,
          labelName: "Enable Chat With Recruiter",
          fieldType: "text",
          isMultiSelect: false,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "career_page_recruiter",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_advance"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 4,
          gridGroup: 1,
          labelName: "Select Recruiter",
          fieldType: "dropdown",
          isMultiSelect: true,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_promotion_video",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_advance"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 5,
          gridGroup: 1,
          labelName: "Job Promotion Video",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_promotion_upload_video",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_advance"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 6,
          gridGroup: 1,
          labelName: "Upload Video",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "total_job_positions",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_config_advance"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 7,
          gridGroup: 1,
          labelName: "No. of Positions",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_name",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Name",
          fieldType: "text",
          isMultiSelect: false,
          options: JSON.stringify(["Optional", "Mandatory", "Hide"]),
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_email",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Email ID",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_phoneNo",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Phone Number",
          fieldType: "text",
          isMultiSelect: false,
          options: JSON.stringify(["Optional", "Mandatory", "Hide"]),
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_linkedIn",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "LinkedIn",
          fieldType: "text",
          isMultiSelect: false,
          options: JSON.stringify(["Optional", "Mandatory", "Hide"]),
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_current_location",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Current Location",
          fieldType: "text",
          isMultiSelect: false,
          options: JSON.stringify(["Optional", "Mandatory", "Hide"]),
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_profile",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Profile Picture",
          fieldType: "text",
          isMultiSelect: false,
          options: JSON.stringify(["Optional", "Hide"]),
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_video_intro",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Short Video Introduction",
          fieldType: "text",
          isMultiSelect: false,
          options: JSON.stringify(["Optional", "Hide"]),
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_cover_later",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Cover Letter",
          fieldType: "text",
          isMultiSelect: false,
          options: JSON.stringify(["Optional", "Mandatory", "Hide"]),
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_resume",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Resume",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "job_applicant_attachments",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_job_applicant"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Attachments",
          fieldType: "text",
          isMultiSelect: false,
          options: JSON.stringify(["Optional", "Hide"]),
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: false,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: true,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "application_received_subject",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_application_received"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Subject",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "application_received_message",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_application_received"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Message",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "application_reject_subject",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_application_reject"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Subject",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          formLibraryId: formLibrary._id,
          key: "application_reject_message",
          companyId: company._id,
          formSubSectionId: subSectionMap["career_application_received"],
          formSectionId: sectionMap["post_promote"],
          sortOrder: 1,
          gridGroup: 1,
          labelName: "Message",
          fieldType: "text",
          isMultiSelect: false,
          options: null,
          isMultiUpload: false,
          maxFileSize: 0,
          allowedFileTypes: null,
          isMandatory: true,
          isSystemDefinedField: true,
          isExcludeFromInternalFilter: true,
          isDisabled: false,
          isDraggabled: true,
          isDeleted: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
      console.log("✅ FormSection seeded.");
    } else {
      console.log("ℹ️ FormConfigField already exist. Skipping seeding.");
    }
  } catch (error) {
    console.error("❌ Seeding error:", error);
  }
};

export default seedDatabase;
